#!/bin/bash
#Steps 4-5
#Purpose: Create (sub-)directories
#Written by: Hannah Dugdale
#Date: 11 January 2021

mkdir -p GITHUB_TEST/1_ANNOTATION/DATA GITHUB_TEST/1_ANNOTATION/RESULTS GITHUB_TEST/1_ANNOTATION/CODE
mkdir -p GITHUB_TEST/2_ALPHABET/DATA GITHUB_TEST/2_ALPHABET/RESULTS GITHUB_TEST/2_ALPHABET/CODE
mkdir -p GITHUB_TEST/3_NUMBERS/DATA GITHUB_TEST/3_NUMBERS/RESULTS GITHUB_TEST/3_NUMBERS/CODE
